[project]
name = "pserver-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "qtframework",
]

[tool.uv.workspace]
members = [
    "qtframework",
]

[tool.uv.sources]
qtframework = { workspace = true }
