id: alora
name: Alora
website: https://www.alora.io/
discord: CHJzZUM
reddit: ""
repository: []
host: "149.56.140.239:54900"
version_id: osrs
status: online
icon: servers/runescape/alora.png
runelite: true
server_type: Custom
rates: Custom
population: High
language: English
description: A popular Old School RuneScape private server
updates_url: https://www.alora.io/forums/forum/14-updates/
updates_forum_mode: true
updates_forum_page_limit: 2
updates_forum_pagination_selector: ".pagination .next a"
updates_fetch_thread_content: true
updates_thread_content_selector: ".post.entry-content"
updates_selectors:
  item: "tr.__topic"
  title: "h4 a.topic_title"
  link: "h4 a.topic_title"
  time: ".desc span[itemprop='dateCreated']"
  preview: ""
downloads:
  - name: Windows (64-bit)
    url: https://www.alora.io/downloads/AloraSetup64.exe
  - name: Windows (32-bit)
    url: https://www.alora.io/downloads/AloraSetup32.exe
  - name: macOS
    url: https://www.alora.io/downloads/Alora.dmg
  - name: M1 Mac
    url: https://www.alora.io/downloads/AloraM1.dmg
  - name: Java (Multi-platform)
    url: https://www.alora.io/downloads/Alora.jar
  - name: Android
    url: https://www.alora.io/downloads/Alora.apk
  - name: iOS/iPhone
    url: https://mobile.alora.io
