id: battlescape
name: Battlescape
website: https://www.battlescape.io/
discord: ""
host: ""
version_id: osrs
status: online
icon: servers/runescape/battlescape.png
server_type: PvP
rates: Custom
population: High
language: English
description: A PvP-focused Old School RuneScape private server
scraping:
  url: https://www.battlescape.io/
  use_browser: true
  cache_duration: 300
  total:
    regex: Online:\s*(\d+)
_metadata:
  source: bundled
  app_version: 1.0.0
  content_hash: ""
  last_updated: ''
