id: battlescape
name: BattleScape
website: https://www.battlescape.io/
discord: 6N3rS9T
reddit: ""
repository: []
host: ""
version_id: osrs
status: online
icon: servers/runescape/battlescape.png
runelite: true
server_type: PvP
rates: Custom
population: High
language: English
description: An Old School RuneScape PvP server
login_url: https://www.battlescape.io/login
register_url: https://www.battlescape.io/register
downloads:
  - name: Web Client
    url: https://www.battlescape.io/game/webclient
  - name: Android Client
    url: https://www.battlescape.io/play?startdl=BattleScape.apk
  - name: Windows (64-bit)
    url: https://www.battlescape.io/play?startdl=BattleScape64.exe
  - name: Windows (32-bit)
    url: https://www.battlescape.io/play?startdl=BattleScape32.exe
  - name: Java (Cross-Platform)
    url: https://www.battlescape.io/play?startdl=BattleScape.jar
_metadata:
  source: bundled
  app_version: 1.0.0
  content_hash: ""
  last_updated: ''
