id: runex
name: RuneX
website: https://rxps.io/
discord: x3m4Dxh
github: ''
host: "51.222.10.23:43594"
version_id: osrs
status: online
icon: servers/runescape/runex.png
server_type: Custom
rates: Custom
population: Unknown
language: English
description: A RuneScape private server with semi-custom content
downloads:
  - name: Windows (64-bit)
    url: https://d2n1q79xme98rn.cloudfront.net/rx_live/RX%20Setup.exe
  - name: Windows (32-bit)
    url: https://d2n1q79xme98rn.cloudfront.net/rx_live/RX%20Setup%2032.exe
  - name: Java (Cross-Platform)
    url: https://d2n1q79xme98rn.cloudfront.net/rx_live/RX%20Launcher.jar
_metadata:
  source: bundled
  app_version: 1.0.0
  content_hash: ""
  last_updated: ''
