id: vidyascape
name: Vidyascape
website: https://vidyascape.org/
discord: y8qb3ZB
reddit: ""
updates_url: https://vidyascape.org/patchnotes
updates_use_js: true
updates_selectors:
  item: div.border-secondary
  title: .card-header
  link: ""
  time: .card-header
  preview: .card-body
repository: []
host: ""
worlds:
  - name: "World 1"
    location: "US (East)"
    host: "50.116.63.13:43594"
  - name: "World 2"
    location: "Sweden (Stockholm)"
    host: "172.234.117.22:43594"
  - name: "World 3"
    location: "Australia (Sydney)"
    host: "172.105.188.37:43594"
version_id: "osrs"
status: online
icon: servers/runescape/vidyascape.jpg
runelite: false
server_type: Custom
rates: Custom
population: Medium
language: English
description: A RuneScape private server with custom content
downloads:
  - name: Windows Client
    url: https://vidyascape.org/downloads
  - name: macOS Client
    url: https://vidyascape.org/downloads
  - name: Linux Client
    url: https://vidyascape.org/downloads
_metadata:
  source: bundled
  app_version: 1.0.0
  content_hash: ""
  last_updated: ''
