id: chromiecraft
name: ChromieCraft
website: https://www.chromiecraft.com/en/
discord: jUdJRhmT3J
host: logon.chromiecraft.com
version_id: wotlk
status: online
icon: servers/wow/chromiecraft.png
realm_name: ''
realm_type: PvP
rates: 1x
population: High
language: English
description: ChromieCraft is a fan-made progressive Wrath of the Lich King server that delves deeper into exploring the original lore of the game.
