id: chromiecraft
name: ChromieCraft
website: https://www.chromiecraft.com/en/
discord: jUdJRhmT3J
host: logon.chromiecraft.com
version_id: wotlk
icon: servers/wow/chromiecraft.png
realm_name:
realm_type: PvP
rates:
population: Medium
language: English
uptime:
description: ChromieCraft is a fan-made experience that delves deeper into exploring the original lore of the game.
