id: elysium
name: Elysium Project
website: https://elysium-project.org/
discord: w6bfD7E
reddit: ElysiumProject
repository: []
host: logon.elysium-project.org
version_id: vanilla
status: online
icon: servers/wow/elysium.png
realm_name: ''
realm_type: PvP
rates: 1x
population: High
language: English
description: Nighthaven PvP is Progressive Vanilla WoW Gaming with Blizz-like content.
  It's Vanilla as you remember it.
register_url: https://elysium-project.org/howtoplay/en
login_url: https://elysium-project.org/howtoplay/en
scraping:
  url: https://elysium-project.org/main/stat
  use_browser: false
  cache_duration: 180  # 3 minutes - moderate rate limiting
  total:
    regex: 'Online</th>\s*<td[^>]*>(\d+)'
  alliance:
    regex: 'alliance_small\.png[^>]*>\s*(\d+)'
  horde:
    regex: 'horde_small\.png[^>]*>\s*(\d+)'
  max_players:
    regex: 'Online Max</th>\s*<td[^>]*>(\d+)'
  uptime:
    regex: '<td>([^<]*\sd\.[^<]*)</td>'
