id: elysium
name: Elysium Project
website: https://elysium-project.org/
discord: w6bfD7E
host: logon.elysium-project.org
version_id: vanilla
icon: servers/wow/elysium.png
realm_name: ''
realm_type: PvP
rates: 1x
population: High
language: English
uptime: ''
description: Nighthaven PvP is Progressive Vanilla WoW Gaming with Blizz-like content.
  It's Vanilla as you remember it.
