id: kronos
name: Kronos
website: https://www.kronos-wow.com/
discord: yzQSnNp
reddit: KronosWoW
host: login.twinstar-wow.com
version_id: vanilla
status: online
icon: servers/wow/kronos.png
realm_name: ''
realm_type: PvP
rates: 1x
population: Medium
language: English
description: Blizzlike Vanilla WoW experience
register_url: https://manager.twinstar-wow.com/registration
login_url: https://manager.twinstar-wow.com/auth/login
scraping:
  url: https://www.kronos-wow.com/
  use_browser: false
  cache_duration: 180  # 3 minutes
  uptime:
    css: '.status2'
    regex: 'Uptime:\s*</strong>(.+?)\s*<br'
