id: retro-wow
name: Retro-WoW
website: https://retro-wow.org/
discord: ShEQcFJd
repository: []
host: logon.retro-wow.org
version_id: vanilla
status: online
icon: servers/wow/retro-wow.png
realm_name: RetroWoW
realm_type: PvE/PvP
rates: Custom (Flexible)
population: Medium
language: English
description: Long-standing custom Vanilla
register_url: https://retro-wow.org/register
login_url: https://retro-wow.org/
