id: retro-wow
name: Retro-WoW
website: https://retro-wow.org/
discord: ShEQcFJd
host: logon.retro-wow.org
version_id: vanilla
status: online
icon: servers/wow/retro-wow.png
realm_name: RetroWoW
realm_type: PvE/PvP
rates: Custom (Flexible)
population: Medium
language: English
uptime: 10+ years
description: Long-standing custom Vanilla
