id: true-wow
name: TrueWoW
website: https://truewow.org/
discord: GqPJkbz
repository: []
host: login.truewow.org
version_id: wotlk
status: online
icon: servers/wow/true-wow.png
realm_name: ''
realm_type: PvP
rates: 1x, 2x, 3x
population: Medium
language: English
description: The oldest and most dedicated WoW server Community since 2010.
# updates_url: https://truewow.org/changelog
# updates_use_js: true
# updates_max_dropdown_options: 12
# updates_limit: 1
# updates_selectors:
#   dropdown: "select[name='logs']"
#   item: "h2.inner"
#   title: "select[name='logs'] option[selected]"
#   link: ""
#   time: "select[name='logs'] option[selected]"
#   preview: ""
downloads:
  - name: Client Download
    url: https://truewow.org/download
register_url: https://truewow.org/forum/ucp.php?mode=register
scraping:
  url: https://truewow.org/status
  use_browser: false
  cache_duration: 180  # 3 minutes - moderate rate limiting
  alliance:
    regex: 'alliance\.gif[^>]*>[^<]*</th>\s*<th>(\d+)'
  horde:
    regex: 'horde\.gif[^>]*>[^<]*</th>\s*<th>(\d+)'
  uptime:
    regex: 'Uptime</th>\s*<td[^>]*>([^<]+)</td>'
