# Old School RuneScape Private Server Definition
id: runescape
name: "RuneScape"
icon: "games/runescape.png"
reddit: "RSPS"

# RuneScape Versions
versions:
  - id: osrs
    name: "Old School RuneScape"
    description: "2007-era RuneScape (Official OSRS)"
    icon: "versions/runescape-osrs.png"

  - id: "317"
    name: "Revision 317"
    description: "May 2005 - Classic retro (23 skills, Barrows)"
    icon: "versions/runescape-317.png"

  - id: "377"
    name: "Revision 377"
    description: "Late 2005/Early 2006 - Post-Construction"
    icon: "versions/runescape-377.png"

  - id: "474"
    name: "Revision 474"
    description: "October 2007 - True 2007scape (GWD, full Wilderness)"
    icon: "versions/runescape-474.png"

  - id: "508"
    name: "Revision 508"
    description: "September 2008 - RuneScape HD (Summoning, HD graphics)"
    icon: "versions/runescape-508.png"

  - id: "562"
    name: "Revision 562"
    description: "Late 2009 - Peak HD era (RuneTek 5)"
    icon: "versions/runescape-562.png"

  - id: "634"
    name: "Revision 634"
    description: "December 2010 - Nex era (Dungeoneering)"
    icon: "versions/runescape-634.png"

  - id: "667"
    name: "Revision 667"
    description: "Mid 2011 - Post free trade return"
    icon: "versions/runescape-667.png"

  - id: "718"
    name: "Revision 718"
    description: "July 2012 - Final Pre-EoC (most popular Pre-EoC)"
    icon: "versions/runescape-718.png"

  - id: "742"
    name: "Revision 742+"
    description: "November 2012+ - Evolution of Combat / RS3"
    icon: "versions/runescape-742.png"

  - id: rs2
    name: "RuneScape 2"
    description: "RuneScape 2 (2004-2007) - Generic"
    icon: "versions/runescape-rs2.png"

  - id: rs3
    name: "RuneScape 3"
    description: "Modern RuneScape / RS3 - Generic"
    icon: "versions/runescape-rs3.png"

# Table columns for RuneScape servers
table_columns:
  - id: name
    label: "Server Name"
    width: stretch

  - id: status
    label: "Status"
    width: content

  - id: address
    label: "Host"
    width: content

  - id: links
    label: "Links"
    width: content

  - id: server_type
    label: "Type"
    width: content

  - id: rates
    label: "XP Rates"
    width: content

  - id: population
    label: "Population"
    width: content

  - id: version
    label: "Version"
    width: content

  - id: language
    label: "Language"
    width: content

  - id: uptime
    label: "Uptime"
    width: content

# Required fields for RuneScape server configs
server_schema:
  - name: name
    type: string
    required: true

  - name: website
    type: string
    required: true

  - name: discord
    type: string
    required: false
    default: ""
    description: "Discord invite code"

  - name: reddit
    type: string
    required: false
    default: ""
    description: "Subreddit name"

  - name: repository
    type: list
    required: false
    default: []
    description: "List of repositories with type (github/gitlab/bitbucket/gitea) and identifier (e.g., 'owner/repo')"

  - name: host
    type: string
    required: false
    default: ""
    description: "Server host/IP"

  - name: worlds
    type: list
    required: false
    default: []
    description: "List of game worlds with name, location, and host. Each world should have 'name' (e.g., 'World 1'), 'location' (e.g., 'US East'), and 'host' (IP:port)"

  - name: version_id
    type: string
    required: true

  - name: status
    type: string
    required: true
    values: [online, offline, maintenance, starting]

  - name: server_type
    type: string
    default: "Economy"
    description: "Economy, PvP, Ironman, etc."

  - name: rates
    type: string
    default: "Custom"
    description: "XP rates (e.g., 1x, 5x, Custom)"

  - name: population
    type: string
    default: "Medium"
    description: "Low, Medium, High, or actual number"

  - name: language
    type: string
    default: "English"

  - name: description
    type: string
    default: ""

  - name: register_url
    type: string
    required: false
    default: ""
    description: "Registration page URL"

  - name: login_url
    type: string
    required: false
    default: ""
    description: "Account login/management URL"

  - name: downloads
    type: list
    required: false
    default: []
    description: "List of client downloads with name and url"

  - name: runelite
    type: boolean
    required: false
    default: false
    description: "Whether the server uses RuneLite client"
